apiVersion: v2
appVersion: "1.0.11"
description: A platform for developing guided interviews and expert systems
name: docassemble
version: 1.0.11
dependencies:
  - name: nginx-ingress
    version: 1.34.2
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: inClusterNGINX,createInClusterNGINX
  - name: minio
    version: 5.0.17
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: inClusterMinio
  - name: rabbitmq
    version: 6.19.2
    repository: https://charts.bitnami.com/bitnami
    condition: inClusterRabbitMQ
