dependencies:
  - name: nginx-ingress
    version: 1.24.4
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: minio
    version: 2.5.16
    repository: https://kubernetes-charts.storage.googleapis.com
