replicas: 2
postgresImage: postgres:10.4
redisImage: redis:latest
timeZone: America/New_York
daImage: jhpyle/docassemble:latest
daHostname: localhost
dbName: docassemble
dbUser: docassemble
dbPassword: abc123
postgresStorage: 5Gi
redisStorage: 5Gi
usingSslTermination: true
rabbitmq:
  rabbitmq:
    password: abc123
    erlangCookie: jmvk83gy7gsbf9kb37gk99hdf2d4jdz
minio:
  persistence:
    size: 10Gi
  mode: distributed
  accessKey: "AKIAIOSFODNN7"
  secretKey: "wJalrXUtnFEMI/K7MDENG/bPxRfiCY"
  replicas: 4
  defaultBucket:
    enabled: true
    name: docassemble-bucket
nginx-ingress:
  rbac.create: true
  controller:
    replicaCount: 2
    nodeSelector:
      beta.kubernetes.io/os: linux
    publishService:
      enabled: true
  defaultBackend:
    nodeSelector:
      beta.kubernetes.io/os: linux
global:
  bucketName: docassemble-bucket
