apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-docassemble-backend-service
spec:
  selector:
    app: {{ .Release.Name }}-docassemble-backend
  ports:
    - port: 8080
      targetPort: 8080
      name: http
    - port: 514
      targetPort: 514
      name: syslog
  type: ClusterIP
