apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-docassemble-backend-service
spec:
  selector:
    app: {{ .Release.Name }}-docassemble-backend
  ports:
    - port: 8082
      targetPort: 8082
      name: http
    - port: 514
      targetPort: 514
      name: syslog
    - port: 25
      targetPort: 25
      name: smtp
  type: ClusterIP
