apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-docassemble
  labels:
    app: {{ .Release.Name }}-docassemble
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-docassemble
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-docassemble
    spec:
      initContainers:
      - name: init-backend
        image: busybox:1.28
        command: ['sh', '-c', 'until wget -q -O /dev/null http://{{ .Release.Name }}-docassemble-backend-service:8080/listlog/health_check?ready=1; do echo waiting for backend; sleep 2; done;']
      containers:
      - name: docassemble
        image: {{ .Values.daImage }}
        imagePullPolicy: Always
        env:
        - name: CONTAINERROLE
          value: "web:celery"
        {{ include "docassemble.commonEnvironment" . }}
        ports:
        - containerPort: 80
        - containerPort: 5000
        - containerPort: 9001
        readinessProbe:
          httpGet:
            path: /health_check?ready=1
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 60
        livenessProbe:
          httpGet:
            path: /health_check
            port: 80
          initialDelaySeconds: 600
          periodSeconds: 60
      terminationGracePeriodSeconds: 120
