{{- if and .Values.inClusterNGINX .Values.exposeWebsockets }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-docassemble-ingress-sticky
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/affinity-mode: "persistent"
    nginx.ingress.kubernetes.io/websocket-services: "{{ .Release.Name }}-docassemble-service"
    nginx.ingress.kubernetes.io/session-cookie-path: "/"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1440m"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1440m"
spec:
  rules:
  - host: {{ .Values.daHostname }}
    http:
      paths:
      - path: /ws(/|$)(.*)
        backend:
          serviceName: {{ .Release.Name }}-docassemble-service
          servicePort: 5000
{{- end }}
