{{- if .Values.inClusterPostgres }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secret
  labels:
    app: {{ .Release.Name }}-postgres
type: Opaque
data:
  POSTGRES_USER: {{ .Values.db.user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.db.password | b64enc | quote }}
{{- end }}
