kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-postgres-pv-claim
  labels:
    app: {{ .Release.Name }}-postgres
spec:
{{- if .Values.minio.persistence.storageClass }}
{{- if (eq "-" .Values.minio.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.minio.persistence.storageClass }}"
{{- end }}
{{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresStorage }}
