{{- if .Values.inClusterPostgres }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-postgres-config
  labels:
    app: {{ .Release.Name }}-postgres
data:
  POSTGRES_DB: {{ .Values.db.name }}
  POSTGRES_USER: {{ .Values.db.user }}
  POSTGRES_PASSWORD: {{ .Values.db.password }}
  PGDATA: /var/lib/postgresql/data/pgdata
{{- end }}
