{{- if .Values.inClusterPostgres }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres-service
  labels:
    app: {{ .Release.Name }}-postgres
spec:
  type: {{ if .Values.db.exposeInternal }}NodePort{{ else }}ClusterIP{{ end }}
  ports:
   - port: 5432
  selector:
   app: {{ .Release.Name }}-postgres
{{- end }}
