apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-docassemble-service
spec:
  selector:
    app: {{ .Release.Name }}-docassemble
  ports:
    - port: 80
      targetPort: 80
      name: http
      protocol: TCP
{{- if .Values.redirectHttp }}
    - port: 8081
      targetPort: 8081
      name: httpredirect
      protocol: TCP
{{- end }}
{{- if .Values.exposeWebsockets }}
    - port: 5000
      targetPort: 5000
      name: wshttp
      protocol: TCP
{{- end }}
{{- if or (not .Values.inClusterNGINX) (.Values.redirectHttp) }}
  type: LoadBalancer
{{- end }}
